blank_issues_enabled: true
contact_links:
  - name: Freicoin Security Policy
    url: https://github.com/tradecraftio/tradecraft/blob/master/SECURITY.md
    about: View security policy
  - name: Freicoin Developers
    url: http://freico.in
    about: Freicoin homepage
