.TH FREICOIN-CLI "1" "February 2015" "freicoin-cli 0.10" 
.SH NAME
freicoin-cli \- a remote procedure call client for Freicoin. 
.SH SYNOPSIS
freicoin-cli [options] <command> [params] \- Send command to Freicoin. 
.TP
freicoin-cli [options] help \- Asks Freicoin for a list of supported commands.
.SH DESCRIPTION
This manual page documents the freicoin-cli program. freicoin-cli is an RPC client used to send commands to Freicoin.

.SH OPTIONS
.TP
\fB\-?\fR
Show the help message.
.TP
\fB\-conf=\fR<file>
Specify configuration file (default: freicoin.conf).
.TP
\fB\-datadir=\fR<dir>
Specify data directory.
.TP
\fB\-testnet\fR
Connect to a Freicoin instance running in testnet mode.
.TP
\fB\-regtest\fR
Connect to a Freicoin instance running in regtest mode (see documentation for -regtest on freicoind).
.TP
\fB\-rpcuser=\fR<user>
Username for JSON\-RPC connections.
.TP
\fB\-rpcpassword=\fR<pw>
Password for JSON\-RPC connections.
.TP
\fB\-rpcport=\fR<port>
Listen for JSON\-RPC connections on <port> (default: 8638 or testnet: 18638).
.TP
\fB\-rpcconnect=\fR<ip>
Send commands to node running on <ip> (default: 127.0.0.1).
.TP
\fB\-rpcssl\fR=\fI1\fR
Use OpenSSL (https) for JSON\-RPC connections (see the Bitcoin Wiki for SSL setup instructions).

.SH "SEE ALSO"
\fBfreicoind\fP, \fBfreicoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
